### ISSUE TITLE
`aria-label` and `title`: using both can cause double speak

### ISSUE THREAD

**Issue by Malvoz** [ignatiusmb/mauss.dev#77]
https://mauss.dev/posts/aria-label-vs-title-attribute:

> The answer is to simply use both `aria-label` and `title` attribute if you need the tooltip

Conveying both to ATs causes double speak with some screen readers (NVDA: https://github.com/nvaccess/nvda/issues/7841).

You _can_ however use both `aria-label` and `title` attribute (to provide a visual tooltip) without causing double speak by hiding `title` from ATs:

```html
<button aria-label="accessible name">
  <span aria-hidden="true" title="visual tooltip that is hidden from ATs to avoid double speak">
   <!-- icon -->
  </span>
</button>
```

**Comment by ignatiusmb** [comment]
Thank you for bringing this to attention. If I understand the issue correctly, some screen readers will double speak when both `aria-title` and `title` with the same content exists in a _separate_ element, what happens if it's just in one element, surely we can't put both `aria-label` and `aria-hidden` together, right?

```html
<button aria-label="name to speak" title="only for tooltip?">something</button>
<!-- or say a span -->
<span aria-label="special word" title="tooltip only?">special word</span>
```
